"use client"

import { useState, useEffect, useCallback } from "react"
import Link from "next/link"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { getScans } from "@/services/scan-service"
import { IScan } from "@/types"
import { FileText, AlertTriangle, CheckCircle, Download } from "lucide-react"
import { toast } from "sonner"

function generateReportHTML(scan: IScan): string {
  const confidence = (scan.confidenceScore * 100).toFixed(1)
  const status = scan.fractureDetected ? "Fracture Detected" : "No Fracture Detected"
  const date = new Date(scan.createdAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit",
  })
  const regions = scan.aiResult?.regions?.join(", ") || "N/A"
  const summary = scan.aiResult?.summary || "No summary available."

  return `<!DOCTYPE html>
<html>
<head><title>Scan Report - BoneFracture AI</title>
<style>
  body { font-family: Arial, sans-serif; padding: 40px; color: #222; }
  h1 { color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 10px; }
  .section { margin: 24px 0; }
  .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
  .label { color: #666; }
  .value { font-weight: bold; }
  img { max-width: 100%; height: auto; border: 1px solid #ddd; margin: 12px 0; border-radius: 4px; }
  .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #ddd; padding-top: 12px; }
</style></head>
<body>
  <h1>BoneFracture AI - Scan Report</h1>
  <p style="color:#666;">AI-Powered Fracture Detection Analysis</p>

  <div class="section">
    <h2>Patient Information</h2>
    <div class="row"><span class="label">Patient ID</span><span class="value">Anonymous</span></div>
    <div class="row"><span class="label">Scan Date</span><span class="value">${date}</span></div>
  </div>

  <div class="section">
    <h2>Detection Results</h2>
    <div class="row"><span class="label">Fracture Status</span><span class="value">${status}</span></div>
    <div class="row"><span class="label">Confidence Score</span><span class="value">${confidence}%</span></div>
    <div class="row"><span class="label">Affected Regions</span><span class="value">${regions}</span></div>
  </div>

  <div class="section">
    <h2>X-Ray Image</h2>
    <img src="${scan.imageUrl.startsWith("http") ? scan.imageUrl : window.location.origin + scan.imageUrl}" alt="X-ray scan" />
  </div>

  <div class="section">
    <h2>AI Analysis Summary</h2>
    <p style="line-height:1.6; color:#444;">${summary}</p>
  </div>

  <div class="footer">
    This report was generated by BoneFracture AI. This is an AI-assisted analysis and should be reviewed by a qualified healthcare professional.
  </div>
</body></html>`
}

export default function ReportsPage() {
  const [scans, setScans] = useState<IScan[]>([])
  const [loading, setLoading] = useState(true)

  const loadScans = useCallback(async () => {
    try {
      const data = await getScans({ limit: 50 })
      setScans(data.scans.filter(s => s.fractureDetected !== undefined))
    } catch {
      toast.error("Failed to load scans")
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    loadScans()
  }, [loadScans])

  function handleDownload(scan: IScan) {
    const html = generateReportHTML(scan)
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `scan-report-${scan._id}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("Report downloaded")
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
        <p className="text-muted-foreground">Download reports for your scans.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Your Reports</CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="space-y-4">
              {Array.from({ length: 5 }).map((_, i) => (
                <Skeleton key={i} className="h-20 w-full rounded-lg" />
              ))}
            </div>
          ) : scans.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <FileText className="mb-4 h-12 w-12 text-muted-foreground/50" />
              <h3 className="mb-2 text-lg font-medium">No reports available</h3>
              <p className="text-sm text-muted-foreground">
                Reports will be available after each scan analysis.
              </p>
              <Link href="/dashboard/upload">
                <Button className="mt-4">Upload Scan</Button>
              </Link>
            </div>
          ) : (
            <div className="space-y-3">
              {scans.map((scan) => (
                <div
                  key={scan._id}
                  className="flex items-center justify-between rounded-lg border border-border/50 p-4 transition-all hover:border-primary/30"
                >
                  <div className="flex items-center gap-4">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                      <FileText className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <p className="text-sm font-medium">
                        Scan Report - {new Date(scan.createdAt).toLocaleDateString("en-US", {
                          year: "numeric", month: "long", day: "numeric",
                        })}
                      </p>
                      <div className="flex items-center gap-2 mt-1">
                        <Badge variant={scan.fractureDetected ? "destructive" : "secondary"} className="text-xs">
                          {scan.fractureDetected ? (
                            <><AlertTriangle className="mr-1 h-3 w-3" /> Fracture</>
                          ) : (
                            <><CheckCircle className="mr-1 h-3 w-3" /> Clear</>
                          )}
                        </Badge>
                        <span className="text-xs text-muted-foreground">
                          {(scan.confidenceScore * 100).toFixed(1)}% confidence
                        </span>
                      </div>
                    </div>
                  </div>

                  <Button variant="outline" size="sm" onClick={() => handleDownload(scan)}>
                    <Download className="mr-2 h-4 w-4" />
                    Download Report
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
