"use client"

import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer"

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: "#1a56db",
    paddingBottom: 12,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a56db",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12,
    color: "#64748b",
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#0f172a",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  label: {
    fontSize: 12,
    color: "#64748b",
  },
  value: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#0f172a",
  },
  image: {
    width: "100%",
    height: 300,
    objectFit: "contain",
    marginVertical: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  summary: {
    fontSize: 11,
    lineHeight: 1.6,
    color: "#334155",
    marginTop: 8,
  },
  notes: {
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 4,
    minHeight: 60,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 10,
    color: "#94a3b8",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 12,
  },
})

interface PDFReportProps {
  patientId: string
  scanDate: string
  fractureDetected: boolean
  confidenceScore: number
  imageUrl: string
  summary: string
  regions?: string[]
  notes?: string
}

export function PDFReport({
  patientId,
  scanDate,
  fractureDetected,
  confidenceScore,
  imageUrl,
  summary,
  regions,
  notes,
}: PDFReportProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>BoneFracture AI - Scan Report</Text>
          <Text style={styles.subtitle}>AI-Powered Fracture Detection Analysis</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Patient Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Patient ID</Text>
            <Text style={styles.value}>{patientId}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Scan Date</Text>
            <Text style={styles.value}>{scanDate}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Detection Results</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Fracture Status</Text>
            <Text style={styles.value}>{fractureDetected ? "Fracture Detected" : "No Fracture Detected"}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Confidence Score</Text>
            <Text style={styles.value}>{(confidenceScore * 100).toFixed(1)}%</Text>
          </View>
          {regions && regions.length > 0 && (
            <View style={styles.row}>
              <Text style={styles.label}>Affected Regions</Text>
              <Text style={styles.value}>{regions.join(", ")}</Text>
            </View>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>X-Ray Image</Text>
          <Image style={styles.image} src={imageUrl} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>AI Analysis Summary</Text>
          <Text style={styles.summary}>{summary}</Text>
        </View>

        {notes && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Doctor&apos;s Notes</Text>
            <View style={styles.notes}>
              <Text style={{ fontSize: 11, color: "#334155" }}>{notes}</Text>
            </View>
          </View>
        )}

        <Text style={styles.footer}>
          This report was generated by BoneFracture AI. This is an AI-assisted analysis and should be reviewed by a qualified healthcare professional.
        </Text>
      </Page>
    </Document>
  )
}
